
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Rizqi
 */
public class Booking extends javax.swing.JFrame {

    /**
     * Creates new form Booking
     */
    String no_booking;

    public Booking() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        datatable();
        setIcon();
        nobooking();
        delete();
        Locale locale = new Locale("id", "ID");
        Locale.setDefault(locale);
    }

    public void delete() {
        try {
            Connection c = koneksi.getKon();
            Statement s = c.createStatement();
            s.executeUpdate("DELETE from tbl_tempo where no_booking=(' " + no_booking + " ');");

        } catch (Exception e) {

        }
    }

    public void nobooking() {
        java.util.Date now = new java.util.Date();
        SimpleDateFormat simpleDateFormat
                = new SimpleDateFormat("ddMMyyyy");
        String thn = simpleDateFormat.format(now);

        txt_nobooking.setText("" + thn + no);
        try {
            Connection c = koneksi.getKon();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery("select * from tbl_booking where no_booking");

            while (r.next()) {

                no = r.getInt("no_booking");
                no++;
                txt_nobooking.setText("" + no);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan");

        }

    }

    public void datatable() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("No");
        tbl.addColumn("Nama Team");
        tbl.addColumn("No. HP");
        tbl.addColumn("Tanggal");
        tbl.addColumn("Jam Masuk");
        tbl.addColumn("Jam Keluar");
        tbl.addColumn("Harga");
        tbl.addColumn("Sisa Bayar");
        tbl_booking.setModel(tbl);

        try {
            Connection c = koneksi.getKon();
            Statement s = c.createStatement();

            String sql = "SELECT * FROM tbl_booking";

            ResultSet r = s.executeQuery(sql);
            while (r.next()) {
                tbl.addRow(new Object[]{
                    r.getInt("no_booking"),
                    r.getString("nama_tim"),
                    r.getString("no_hp"),
                    r.getString("tanggal"),
                    r.getString("jam_masuk"),
                    r.getString("jam_keluar"),
                    r.getInt("harga"),
                    r.getInt("Sisa")

                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Image/LOGO.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_noHp2 = new javax.swing.JLabel();
        txt_no_book1 = new javax.swing.JLabel();
        txt_nama_team1 = new javax.swing.JLabel();
        rp2 = new javax.swing.JLabel();
        rp1 = new javax.swing.JLabel();
        rp = new javax.swing.JLabel();
        txt_tanggal1 = new javax.swing.JLabel();
        txt_noHp1 = new javax.swing.JLabel();
        txt_tgl = new com.toedter.calendar.JDateChooser();
        cb_keluar = new javax.swing.JComboBox<>();
        cb_masuk = new javax.swing.JComboBox<>();
        txt_sisa = new javax.swing.JTextField();
        txt_bayar = new javax.swing.JTextField();
        txt_harga = new javax.swing.JTextField();
        txt_nohp = new javax.swing.JTextField();
        txt_namateam = new javax.swing.JTextField();
        txt_nobooking = new javax.swing.JTextField();
        txt_noHp = new javax.swing.JLabel();
        txt_tanggal = new javax.swing.JLabel();
        txt_nama_team = new javax.swing.JLabel();
        txt_no_book = new javax.swing.JLabel();
        bg_bawahabu1 = new javax.swing.JLabel();
        bg_bawahabu2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_booking = new javax.swing.JTable();
        btn_simpan = new javax.swing.JLabel();
        btn_cari = new javax.swing.JLabel();
        btn_hapus = new javax.swing.JLabel();
        btn_cetak = new javax.swing.JLabel();
        bar_atas = new javax.swing.JLabel();
        bg_bawahbok = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, -1, -1));

        txt_noHp2.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 20)); // NOI18N
        txt_noHp2.setForeground(new java.awt.Color(30, 51, 69));
        txt_noHp2.setText("Sisa Bayar");
        getContentPane().add(txt_noHp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 275, -1, -1));

        txt_no_book1.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 20)); // NOI18N
        txt_no_book1.setForeground(new java.awt.Color(30, 51, 69));
        txt_no_book1.setText("Jam Masuk");
        getContentPane().add(txt_no_book1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 95, -1, -1));

        txt_nama_team1.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 20)); // NOI18N
        txt_nama_team1.setForeground(new java.awt.Color(30, 51, 69));
        txt_nama_team1.setText("Jam Keluar");
        getContentPane().add(txt_nama_team1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 135, -1, -1));

        rp2.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 20)); // NOI18N
        rp2.setForeground(new java.awt.Color(129, 143, 155));
        rp2.setText("Rp.");
        getContentPane().add(rp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 280, -1, -1));

        rp1.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 20)); // NOI18N
        rp1.setForeground(new java.awt.Color(129, 143, 155));
        rp1.setText("Rp.");
        getContentPane().add(rp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 235, -1, -1));

        rp.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 20)); // NOI18N
        rp.setForeground(new java.awt.Color(129, 143, 155));
        rp.setText("Rp.");
        getContentPane().add(rp, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 190, -1, -1));

        txt_tanggal1.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 20)); // NOI18N
        txt_tanggal1.setForeground(new java.awt.Color(30, 51, 69));
        txt_tanggal1.setText("Harga");
        getContentPane().add(txt_tanggal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 185, -1, -1));

        txt_noHp1.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 20)); // NOI18N
        txt_noHp1.setForeground(new java.awt.Color(30, 51, 69));
        txt_noHp1.setText("Uang Muka");
        getContentPane().add(txt_noHp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, -1, -1));

        txt_tgl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_tglMouseClicked(evt);
            }
        });
        txt_tgl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_tglKeyPressed(evt);
            }
        });
        getContentPane().add(txt_tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 160, 30));

        cb_keluar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cb_keluar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "09.00", "10.00", "11.00", "12.00", "13.00", "14.00", "15.00", "16.00", "17.00", "18.00", "19.00", "20.00", "21.00", "22.00", "23.00" }));
        cb_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_keluarActionPerformed(evt);
            }
        });
        cb_keluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cb_keluarKeyPressed(evt);
            }
        });
        getContentPane().add(cb_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 90, 30));

        cb_masuk.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cb_masuk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08.00", "09.00", "10.00", "11.00", "12.00", "13.00", "14.00", "15.00", "16.00", "17.00", "18.00", "19.00", "20.00", "21.00", "22.00" }));
        cb_masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_masukActionPerformed(evt);
            }
        });
        cb_masuk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cb_masukKeyPressed(evt);
            }
        });
        getContentPane().add(cb_masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 90, 30));

        txt_sisa.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        txt_sisa.setForeground(new java.awt.Color(75, 75, 77));
        txt_sisa.setCaretColor(new java.awt.Color(30, 51, 69));
        txt_sisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_sisaKeyPressed(evt);
            }
        });
        getContentPane().add(txt_sisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 130, 30));

        txt_bayar.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        txt_bayar.setForeground(new java.awt.Color(75, 75, 77));
        txt_bayar.setCaretColor(new java.awt.Color(30, 51, 69));
        txt_bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_bayarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_bayarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_bayarKeyTyped(evt);
            }
        });
        getContentPane().add(txt_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 225, 130, 30));

        txt_harga.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        txt_harga.setForeground(new java.awt.Color(75, 75, 77));
        txt_harga.setCaretColor(new java.awt.Color(30, 51, 69));
        txt_harga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_hargaKeyPressed(evt);
            }
        });
        getContentPane().add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 130, 30));

        txt_nohp.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        txt_nohp.setForeground(new java.awt.Color(75, 75, 77));
        txt_nohp.setCaretColor(new java.awt.Color(30, 51, 69));
        txt_nohp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nohpKeyPressed(evt);
            }
        });
        getContentPane().add(txt_nohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 160, 30));

        txt_namateam.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        txt_namateam.setForeground(new java.awt.Color(75, 75, 77));
        txt_namateam.setCaretColor(new java.awt.Color(30, 51, 69));
        txt_namateam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namateamActionPerformed(evt);
            }
        });
        txt_namateam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_namateamKeyPressed(evt);
            }
        });
        getContentPane().add(txt_namateam, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 160, 30));

        txt_nobooking.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        txt_nobooking.setForeground(new java.awt.Color(75, 75, 77));
        txt_nobooking.setCaretColor(new java.awt.Color(30, 51, 69));
        txt_nobooking.setNextFocusableComponent(txt_namateam);
        txt_nobooking.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_nobookingFocusGained(evt);
            }
        });
        txt_nobooking.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nobookingKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nobookingKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nobooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 160, 30));

        txt_noHp.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 20)); // NOI18N
        txt_noHp.setForeground(new java.awt.Color(30, 51, 69));
        txt_noHp.setText("No HP");
        getContentPane().add(txt_noHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 245, -1, -1));

        txt_tanggal.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 20)); // NOI18N
        txt_tanggal.setForeground(new java.awt.Color(30, 51, 69));
        txt_tanggal.setText("Tanggal");
        getContentPane().add(txt_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 194, -1, -1));

        txt_nama_team.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 20)); // NOI18N
        txt_nama_team.setForeground(new java.awt.Color(30, 51, 69));
        txt_nama_team.setText("Nama Team");
        getContentPane().add(txt_nama_team, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 144, -1, -1));

        txt_no_book.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 20)); // NOI18N
        txt_no_book.setForeground(new java.awt.Color(30, 51, 69));
        txt_no_book.setText("No Booking");
        getContentPane().add(txt_no_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 94, -1, -1));

        bg_bawahabu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bar_abu_abu.png"))); // NOI18N
        getContentPane().add(bg_bawahabu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        bg_bawahabu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bar_abu_abu.png"))); // NOI18N
        getContentPane().add(bg_bawahabu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, -1));

        tbl_booking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_booking);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 690, 170));

        btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bookingbutton/Simpan_off.png"))); // NOI18N
        btn_simpan.setToolTipText("Simpan Data");
        btn_simpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_simpan.setFocusTraversalPolicyProvider(true);
        btn_simpan.setNextFocusableComponent(txt_namateam);
        btn_simpan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn_simpanFocusGained(evt);
            }
        });
        btn_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_simpanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_simpanMouseEntered(evt);
            }
        });
        btn_simpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_simpanKeyPressed(evt);
            }
        });
        getContentPane().add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 323, -1, -1));

        btn_cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/btn_cari.png"))); // NOI18N
        btn_cari.setToolTipText("Cari Data Berdasarkan No Booking");
        btn_cari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cariMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cariMouseEntered(evt);
            }
        });
        getContentPane().add(btn_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 323, -1, -1));

        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/btn_hapus.png"))); // NOI18N
        btn_hapus.setToolTipText("Hapus Data Berdasarkan No Booking");
        btn_hapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_hapusMouseEntered(evt);
            }
        });
        getContentPane().add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 323, -1, -1));

        btn_cetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bookingbutton/Cetak_off.png"))); // NOI18N
        btn_cetak.setToolTipText("Cetak Struk Booking");
        btn_cetak.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cetak.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn_cetakFocusGained(evt);
            }
        });
        btn_cetak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cetakMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cetakMouseEntered(evt);
            }
        });
        getContentPane().add(btn_cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 323, -1, -1));

        bar_atas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bar_atas_book.png"))); // NOI18N
        bar_atas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bar_atasMouseDragged(evt);
            }
        });
        bar_atas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bar_atasMousePressed(evt);
            }
        });
        getContentPane().add(bar_atas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        bg_bawahbok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bg_bawah_1.png"))); // NOI18N
        bg_bawahbok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bg_bawahbokMouseEntered(evt);
            }
        });
        getContentPane().add(bg_bawahbok, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int xx, xy;
    private void bar_atasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bar_atasMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_bar_atasMousePressed

    private void bar_atasMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bar_atasMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_bar_atasMouseDragged

    private void btn_simpanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpanMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Bookingbutton/Simpan_on.png"));
        btn_simpan.setIcon(II);
    }//GEN-LAST:event_btn_simpanMouseEntered

    private void btn_hapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Bookingbutton/btn_hapusOn.png"));
        btn_hapus.setIcon(II);
    }//GEN-LAST:event_btn_hapusMouseEntered

    private void btn_cariMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cariMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Bookingbutton/btn_cariOn.png"));
        btn_cari.setIcon(II);
    }//GEN-LAST:event_btn_cariMouseEntered

    private void btn_cetakMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cetakMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Bookingbutton/Cetak_on.png"));
        btn_cetak.setIcon(II);
    }//GEN-LAST:event_btn_cetakMouseEntered

    private void bg_bawahbokMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg_bawahbokMouseEntered
        ImageIcon IIa = new ImageIcon(getClass().getResource("/Bookingbutton/Simpan_off.png"));
        btn_simpan.setIcon(IIa);

        ImageIcon IIb = new ImageIcon(getClass().getResource("Image/btn_hapus.png"));
        btn_hapus.setIcon(IIb);

        ImageIcon IIc = new ImageIcon(getClass().getResource("/Image/btn_cari.png"));
        btn_cari.setIcon(IIc);

        ImageIcon IId = new ImageIcon(getClass().getResource("/Bookingbutton/Cetak_off.png"));
        btn_cetak.setIcon(IId);
    }//GEN-LAST:event_bg_bawahbokMouseEntered
    int a, b;
    private void cb_masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_masukActionPerformed
        if (cb_masuk.getSelectedIndex() == 0) {
            a = 80000;
            b = 8;
        }
        if (cb_masuk.getSelectedIndex() == 1) {
            a = 80000;
            b = 9;

        }
        if (cb_masuk.getSelectedIndex() == 2) {
            a = 80000;
            b = 10;
        }
        if (cb_masuk.getSelectedIndex() == 3) {
            a = 80000;
            b = 11;
        }
        if (cb_masuk.getSelectedIndex() == 4) {
            a = 80000;
            b = 12;
        }
        if (cb_masuk.getSelectedIndex() == 5) {
            a = 80000;
            b = 13;
        }
        if (cb_masuk.getSelectedIndex() == 6) {
            a = 80000;
            b = 14;
        }
        if (cb_masuk.getSelectedIndex() == 7) {
            a = 80000;
            b = 15;
        }
        if (cb_masuk.getSelectedIndex() == 8) {
            a = 80000;
            b = 16;
        }
        if (cb_masuk.getSelectedIndex() == 9) {
            a = 80000;
            b = 17;
        }
        if (cb_masuk.getSelectedIndex() == 10) {
            a = 110000;
            b = 18;
        }
        if (cb_masuk.getSelectedIndex() == 11) {
            a = 110000;
            b = 19;
        }
        if (cb_masuk.getSelectedIndex() == 12) {
            a = 110000;
            b = 20;
        }
        if (cb_masuk.getSelectedIndex() == 13) {
            a = 110000;
            b = 21;
        }
        if (cb_masuk.getSelectedIndex() == 14) {
            a = 110000;
            b = 22;
        }

    }//GEN-LAST:event_cb_masukActionPerformed
    int c, total, jam;
    private void cb_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_keluarActionPerformed
        if (cb_keluar.getSelectedIndex() == 0) {
            c = 9;
            jam = c - b;
            total = (c - b) * a;
            txt_harga.setText("" + total);
        }
        if (cb_keluar.getSelectedIndex() == 1) {
            c = 10;
            jam = c - b;
            total = (c - b) * a;
            txt_harga.setText("" + total);
        }
        if (cb_keluar.getSelectedIndex() == 2) {
            c = 11;
            jam = c - b;
            total = (c - b) * a;
            txt_harga.setText("" + total);
        }
        if (cb_keluar.getSelectedIndex() == 3) {
            c = 12;
            jam = c - b;
            total = (c - b) * a;
            txt_harga.setText("" + total);
        }
        if (cb_keluar.getSelectedIndex() == 4) {
            c = 13;
            jam = c - b;
            total = (c - b) * a;
            txt_harga.setText("" + total);
        }
        if (cb_keluar.getSelectedIndex() == 5) {
            c = 14;
            jam = c - b;
            total = (c - b) * a;
            txt_harga.setText("" + total);
        }
        if (cb_keluar.getSelectedIndex() == 6) {
            c = 15;
            jam = c - b;
            total = (c - b) * a;
            txt_harga.setText("" + total);
        }
        if (cb_keluar.getSelectedIndex() == 7) {
            c = 16;
            jam = c - b;
            total = (c - b) * a;
            txt_harga.setText("" + total);
        }
        if (cb_keluar.getSelectedIndex() == 8) {
            c = 17;
            jam = c - b;
            total = (c - b) * a;
            txt_harga.setText("" + total);
        }
        if (cb_keluar.getSelectedIndex() == 9) {
            c = 18;
            jam = c - b;
            total = (c - b) * a;
            txt_harga.setText("" + total);
        }
        if (cb_keluar.getSelectedIndex() == 10) {
            c = 19;
            jam = c - b;
            total = (c - b) * a;
            txt_harga.setText("" + total);
        }
        if (cb_keluar.getSelectedIndex() == 11) {
            c = 20;
            jam = c - b;
            total = (c - b) * a;
            txt_harga.setText("" + total);
        }
        if (cb_keluar.getSelectedIndex() == 12) {
            c = 21;
            jam = c - b;
            total = (c - b) * a;
            txt_harga.setText("" + total);
        }
        if (cb_keluar.getSelectedIndex() == 13) {
            c = 22;
            jam = c - b;
            total = (c - b) * a;
            txt_harga.setText("" + total);
        }
        if (cb_keluar.getSelectedIndex() == 14) {
            c = 23;
            jam = c - b;
            total = (c - b) * a;
            txt_harga.setText("" + total);
        }
    }//GEN-LAST:event_cb_keluarActionPerformed
    int jumlah;
    private void txt_bayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_bayarKeyReleased
        int harga = Integer.parseInt(txt_harga.getText());
        int bayar = Integer.parseInt(txt_bayar.getText());

        jumlah = harga - bayar;

        String sisa = String.valueOf(jumlah);
        txt_sisa.setText(sisa);
    }//GEN-LAST:event_txt_bayarKeyReleased

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked
    int no = 0;
    private void btn_simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpanMouseClicked
        no_booking = txt_nobooking.getText();
        no = Integer.parseInt(no_booking);
        String nama_tim = txt_namateam.getText();
        String no_hp = txt_nohp.getText();
        String jam_masuk = (String) cb_masuk.getSelectedItem();
        String jam_keluar = (String) cb_keluar.getSelectedItem();
        String harga = txt_harga.getText();
        String sisa = txt_sisa.getText();
        //   String transaksi = "No";
        java.sql.Date tanggal = new java.sql.Date(txt_tgl.getDate().getTime());

        try {

            Connection c = koneksi.getKon(); //memanggil fungsi koneksi database
            Statement s = c.createStatement(); //membuat statment
            //memasukan data yg diinputkan ke database db_futsal tabel tbl_booking
            s.executeUpdate("Insert into tbl_booking VALUES (' " + no + " ', ' " + nama_tim + " ' , ' " + no_hp + " ', ' " + tanggal + " ', ' " + jam_masuk + " ', ' " + jam_keluar + " ', ' " + harga + " ', ' " + sisa + " ', ' " + jam + " ');");
            s.executeUpdate("Insert into tbl_tempo VALUES (' " + no + " ', ' " + nama_tim + " ' , ' " + no_hp + " ', ' " + tanggal + " ', ' " + jam_masuk + " ', ' " + jam_keluar + " ', ' " + harga + " ', ' " + sisa + " ', ' " + jam + " ');");

            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
        } catch (Exception t) {

            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan");
        }
        //memanggil fungsi datatable untuk mengupdate data pada table
        datatable();

        txt_namateam.setText("");
        txt_nohp.setText("");
        txt_harga.setText("");
        txt_bayar.setText("");
        txt_sisa.setText("");
        cb_masuk.setSelectedItem("08.00");
        cb_keluar.setSelectedItem("09.00");
        txt_harga.setText("");


    }//GEN-LAST:event_btn_simpanMouseClicked


    private void btn_hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusMouseClicked
        no = Integer.parseInt(txt_nobooking.getText());
        try {
            Connection c = koneksi.getKon();
            Statement s = c.createStatement();
            //statement menghapus data pada tabel sesuai nomor booking yg diinputkan
            s.executeUpdate("DELETE from tbl_booking where no_booking=(' " + no + " ');");
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");

            txt_namateam.setText("");
            txt_nohp.setText("");
            cb_masuk.setSelectedItem("08.00");
            cb_keluar.setSelectedItem("09.00");
            txt_harga.setText("");
            txt_nama_team.requestFocus();

        } catch (Exception t) {
            JOptionPane.showMessageDialog(null, "Data Gagal Dihapus");
        }
        datatable();
    }//GEN-LAST:event_btn_hapusMouseClicked

    private void btn_cariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cariMouseClicked
        txt_nobooking.setEditable(true);
        no = Integer.parseInt(txt_nobooking.getText());

        try {
            Connection c = koneksi.getKon();
            Statement s = c.createStatement();
            //membuat statement untuk mencari data sesuai no booking
            ResultSet r = s.executeQuery("select * from tbl_booking where " + "no_booking=' " + no + " ' ");

            DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("No");
            tbl.addColumn("Nama Team");
            tbl.addColumn("No. HP");
            tbl.addColumn("Tanggal");
            tbl.addColumn("Jam Masuk");
            tbl.addColumn("Jam Keluar");
            tbl.addColumn("Harga");
            tbl.addColumn("Sisa Bayar");
            tbl_booking.setModel(tbl);
            //mengakses data pada tabel tbl_booking database
            while (r.next()) {
                tbl.addRow(new Object[]{
                    r.getInt("no_booking"),
                    r.getString("nama_tim"),
                    r.getString("no_hp"),
                    r.getString("tanggal"),
                    r.getString("jam_masuk"),
                    r.getString("jam_keluar"),
                    r.getInt("harga"),
                    r.getInt("Sisa")
                });
                tbl_booking.setModel(tbl);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_btn_cariMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        txt_namateam.requestFocus();
        nobooking();

    }//GEN-LAST:event_formWindowActivated

    private void btn_cetakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cetakMouseClicked
        // TODO add your handling code here:
        try {

            //String NamaFile = "./src/newBooking.jrxml";
            
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/db_futsal", "root", "");

            InputStream file = getClass().getResourceAsStream("/newBooking.jrxml");
            JasperDesign jasperDesign = JRXmlLoader.load(file);
            
            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
            Map<String, Object> par = new HashMap<String, Object>();
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, par, koneksi);
            JasperViewer.viewReport(jasperPrint, false);
            delete();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "tidak dapat menampilkan laporan");
        }
    }//GEN-LAST:event_btn_cetakMouseClicked

    private void txt_nobookingFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nobookingFocusGained

    }//GEN-LAST:event_txt_nobookingFocusGained

    private void txt_bayarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_bayarKeyTyped
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            txt_namateam.requestFocus();
            evt.consume();
        }
    }//GEN-LAST:event_txt_bayarKeyTyped

    private void btn_cetakFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_cetakFocusGained
        txt_nama_team.setFocusable(true);
    }//GEN-LAST:event_btn_cetakFocusGained

    private void btn_simpanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_simpanFocusGained
        txt_nama_team.setFocusable(true);
    }//GEN-LAST:event_btn_simpanFocusGained

    private void txt_namateamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namateamActionPerformed

    }//GEN-LAST:event_txt_namateamActionPerformed

    private void txt_tglMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_tglMouseClicked

    }//GEN-LAST:event_txt_tglMouseClicked

    private void txt_nobookingKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nobookingKeyTyped

    }//GEN-LAST:event_txt_nobookingKeyTyped

    private void txt_namateamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_namateamKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_tgl.requestFocus();
            evt.consume();
            //JOptionPane.showMessageDialog(null, "ENTER DITAKAN");
        }

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_namateam.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Nama Team tidak boleh kosong");
                txt_namateam.requestFocus();
            }
        }
    

    }//GEN-LAST:event_txt_namateamKeyPressed

    private void cb_masukKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cb_masukKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cb_keluar.requestFocus();
            evt.consume();
        }
    }//GEN-LAST:event_cb_masukKeyPressed

    private void cb_keluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cb_keluarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_bayar.requestFocus();
            evt.consume();
        }
    }//GEN-LAST:event_cb_keluarKeyPressed

    private void txt_hargaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_hargaKeyPressed
        
    }//GEN-LAST:event_txt_hargaKeyPressed

    private void txt_bayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_bayarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_sisa.requestFocus();
            evt.consume();
        }
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_bayar.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Uang Muka tidak boleh kosong");
                txt_bayar.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_bayarKeyPressed

    private void txt_nobookingKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nobookingKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_namateam.requestFocus();
            evt.consume();
        }
    }//GEN-LAST:event_txt_nobookingKeyPressed

    private void txt_sisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sisaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btn_simpan.requestFocus();
            evt.consume();
        }
        
    }//GEN-LAST:event_txt_sisaKeyPressed

    private void btn_simpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_simpanKeyPressed

    }//GEN-LAST:event_btn_simpanKeyPressed

    private void txt_tglKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tglKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_nohp.requestFocus();
            evt.consume();
        }
    }//GEN-LAST:event_txt_tglKeyPressed

    private void txt_nohpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nohpKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_nohp.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Nomor HP tidak boleh kosong");
                txt_nohp.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_nohpKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bar_atas;
    private javax.swing.JLabel bg_bawahabu1;
    private javax.swing.JLabel bg_bawahabu2;
    private javax.swing.JLabel bg_bawahbok;
    private javax.swing.JLabel btn_cari;
    private javax.swing.JLabel btn_cetak;
    private javax.swing.JLabel btn_hapus;
    private javax.swing.JLabel btn_simpan;
    private javax.swing.JComboBox<String> cb_keluar;
    private javax.swing.JComboBox<String> cb_masuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rp;
    private javax.swing.JLabel rp1;
    private javax.swing.JLabel rp2;
    private javax.swing.JTable tbl_booking;
    private javax.swing.JTextField txt_bayar;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JLabel txt_nama_team;
    private javax.swing.JLabel txt_nama_team1;
    private javax.swing.JTextField txt_namateam;
    private javax.swing.JLabel txt_noHp;
    private javax.swing.JLabel txt_noHp1;
    private javax.swing.JLabel txt_noHp2;
    private javax.swing.JLabel txt_no_book;
    private javax.swing.JLabel txt_no_book1;
    private javax.swing.JTextField txt_nobooking;
    private javax.swing.JTextField txt_nohp;
    private javax.swing.JTextField txt_sisa;
    private javax.swing.JLabel txt_tanggal;
    private javax.swing.JLabel txt_tanggal1;
    private com.toedter.calendar.JDateChooser txt_tgl;
    // End of variables declaration//GEN-END:variables
}
