/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class cari extends javax.swing.JFrame {

    /**
     * Creates new form cari
     */
    public cari() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_no_book = new javax.swing.JLabel();
        txt_nobooking = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_no_book.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 20)); // NOI18N
        txt_no_book.setForeground(new java.awt.Color(30, 51, 69));
        txt_no_book.setText("No Booking");
        jPanel1.add(txt_no_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        txt_nobooking.setEditable(false);
        txt_nobooking.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        txt_nobooking.setForeground(new java.awt.Color(75, 75, 77));
        txt_nobooking.setCaretColor(new java.awt.Color(30, 51, 69));
        txt_nobooking.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_nobookingFocusGained(evt);
            }
        });
        txt_nobooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nobookingActionPerformed(evt);
            }
        });
        txt_nobooking.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nobookingKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nobookingKeyTyped(evt);
            }
        });
        jPanel1.add(txt_nobooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 160, 30));

        jButton1.setText("OK");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 160));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nobookingFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nobookingFocusGained

    }//GEN-LAST:event_txt_nobookingFocusGained

    private void txt_nobookingKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nobookingKeyPressed
      
    }//GEN-LAST:event_txt_nobookingKeyPressed

    private void txt_nobookingKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nobookingKeyTyped

    }//GEN-LAST:event_txt_nobookingKeyTyped

    private void txt_nobookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nobookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nobookingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txt_no_book;
    private javax.swing.JTextField txt_nobooking;
    // End of variables declaration//GEN-END:variables
}
