
import AppPackage.AnimationClass;
import java.awt.Color;
import java.awt.Frame;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import java.awt.Window;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Rizqi
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        showDate();
        showMonth();
        setIcon();

    }

    void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd");
        txt_Tanggal.setText(s.format(d));
    }

    void showMonth() {
        Date e = new Date();
        SimpleDateFormat b = new SimpleDateFormat("LLLL YYYY");
        txt_BulanTahun.setText(b.format(e).toUpperCase());

    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Image/LOGO.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_BulanTahun = new javax.swing.JLabel();
        txt_Tanggal = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        bar_atas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Version = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bg_nutopbarbiru1 = new javax.swing.JLabel();
        pilih_laporan = new javax.swing.JLabel();
        txt_laporan = new javax.swing.JLabel();
        trans_laporan = new javax.swing.JLabel();
        laporan_0 = new javax.swing.JLabel();
        bg_nutopbarbiru = new javax.swing.JLabel();
        wasit_0 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_trans = new javax.swing.JLabel();
        pilih_trans = new javax.swing.JLabel();
        trans_transkasi = new javax.swing.JLabel();
        transaksi_0 = new javax.swing.JLabel();
        pilih_booking = new javax.swing.JLabel();
        txt_booking = new javax.swing.JLabel();
        trans_book = new javax.swing.JLabel();
        booking_0 = new javax.swing.JLabel();
        pilih_jadwal = new javax.swing.JLabel();
        txt_jadwal = new javax.swing.JLabel();
        trans_jadwal = new javax.swing.JLabel();
        jadwal_0 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        user1 = new javax.swing.JLabel();
        bar_samping = new javax.swing.JLabel();
        bg_bawah = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 564));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_BulanTahun.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 17)); // NOI18N
        txt_BulanTahun.setForeground(new java.awt.Color(30, 51, 69));
        txt_BulanTahun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_BulanTahun.setText("JANUARI 2018");
        getContentPane().add(txt_BulanTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(847, 260, 132, -1));

        txt_Tanggal.setFont(new java.awt.Font("Arial Narrow", 0, 110)); // NOI18N
        txt_Tanggal.setForeground(new java.awt.Color(30, 51, 69));
        txt_Tanggal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_Tanggal.setText("01");
        getContentPane().add(txt_Tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(848, 144, 132, -1));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close_off_1.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, -1, -1));

        min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/min_1.png"))); // NOI18N
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minMouseEntered(evt);
            }
        });
        getContentPane().add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(949, 0, -1, -1));

        bar_atas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bar_atas.png"))); // NOI18N
        bar_atas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bar_atas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bar_atasMouseDragged(evt);
            }
        });
        bar_atas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bar_atasMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bar_atasMousePressed(evt);
            }
        });
        getContentPane().add(bar_atas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(742, 552, -1, -1));

        Version.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        Version.setForeground(new java.awt.Color(30, 51, 69));
        Version.setText("Futsal App, versi 1.1.0");
        getContentPane().add(Version, new org.netbeans.lib.awtextra.AbsoluteConstraints(797, 490, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/drag.png"))); // NOI18N
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 551, -1, -1));

        bg_nutopbarbiru1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bg_bawah.png"))); // NOI18N
        getContentPane().add(bg_nutopbarbiru1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 446, 660, 120));

        pilih_laporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pilih_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pilih_laporanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pilih_laporanMouseEntered(evt);
            }
        });
        getContentPane().add(pilih_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 397, 410, 50));

        txt_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/txt_Laporan_1.png"))); // NOI18N
        getContentPane().add(txt_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, -1));

        trans_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/trans_laporan.png"))); // NOI18N
        trans_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trans_laporanMouseClicked(evt);
            }
        });
        getContentPane().add(trans_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 390, -1, 140));

        laporan_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/laporan_on.png"))); // NOI18N
        laporan_0.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(laporan_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 299, 450, -1));

        bg_nutopbarbiru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bg_bawah.png"))); // NOI18N
        getContentPane().add(bg_nutopbarbiru, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 287, 430, 110));

        wasit_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/wasittttt.png"))); // NOI18N
        wasit_0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        wasit_0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wasit_0MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                wasit_0MouseEntered(evt);
            }
        });
        getContentPane().add(wasit_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(832, 296, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/kalender.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 114, -1, -1));

        txt_trans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/txt_trans_1.png"))); // NOI18N
        getContentPane().add(txt_trans, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, -1, -1));

        pilih_trans.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pilih_trans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pilih_transMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pilih_transMouseEntered(evt);
            }
        });
        getContentPane().add(pilih_trans, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, 200, 70));

        trans_transkasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bar_trns_transak.png"))); // NOI18N
        trans_transkasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trans_transkasiMouseClicked(evt);
            }
        });
        getContentPane().add(trans_transkasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 365, -1, -1));

        transaksi_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/transaksi_on.png"))); // NOI18N
        transaksi_0.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        transaksi_0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transaksi_0MouseEntered(evt);
            }
        });
        getContentPane().add(transaksi_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 108, -1, -1));

        pilih_booking.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pilih_booking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pilih_bookingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pilih_bookingMouseEntered(evt);
            }
        });
        getContentPane().add(pilih_booking, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 230, 190, 60));

        txt_booking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/txt_Booking.png"))); // NOI18N
        getContentPane().add(txt_booking, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        trans_book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bar_trns.png"))); // NOI18N
        trans_book.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        trans_book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trans_bookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                trans_bookMouseEntered(evt);
            }
        });
        getContentPane().add(trans_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 230, -1, -1));

        booking_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/booking_on.png"))); // NOI18N
        booking_0.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        booking_0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                booking_0MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                booking_0MouseEntered(evt);
            }
        });
        getContentPane().add(booking_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 114, -1, -1));

        pilih_jadwal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pilih_jadwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pilih_jadwalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pilih_jadwalMouseEntered(evt);
            }
        });
        getContentPane().add(pilih_jadwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 190, 60));

        txt_jadwal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/txt_Jadwal_1.png"))); // NOI18N
        getContentPane().add(txt_jadwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, -1, -1));

        trans_jadwal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bar_trns.png"))); // NOI18N
        trans_jadwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                trans_jadwalMouseEntered(evt);
            }
        });
        getContentPane().add(trans_jadwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, -1));

        jadwal_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/jadwal_on.png"))); // NOI18N
        jadwal_0.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jadwal_0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jadwal_0MouseEntered(evt);
            }
        });
        getContentPane().add(jadwal_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 114, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image.FormLoading/user.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 170, -1, -1));

        user1.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        user1.setForeground(new java.awt.Color(242, 242, 242));
        user1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user1.setText("Admin");
        getContentPane().add(user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 305, 150, -1));

        bar_samping.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bar_samping.png"))); // NOI18N
        getContentPane().add(bar_samping, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        bg_bawah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bg_bawah.png"))); // NOI18N
        bg_bawah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bg_bawahMouseEntered(evt);
            }
        });
        getContentPane().add(bg_bawah, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        setSize(new java.awt.Dimension(1012, 564));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void booking_0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booking_0MouseEntered


    }//GEN-LAST:event_booking_0MouseEntered

    int xx, xy;
    private void bar_atasMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bar_atasMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_bar_atasMouseDragged

    private void bar_atasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bar_atasMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_bar_atasMousePressed

    private void wasit_0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wasit_0MouseClicked
        Music mus = new Music();
        mus.setVisible(true);


    }//GEN-LAST:event_wasit_0MouseClicked

    private void booking_0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booking_0MouseClicked
        Booking booking = new Booking();
        booking.setVisible(true);
    }//GEN-LAST:event_booking_0MouseClicked

    private void jadwal_0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jadwal_0MouseEntered

    }//GEN-LAST:event_jadwal_0MouseEntered

    private void transaksi_0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksi_0MouseEntered

    }//GEN-LAST:event_transaksi_0MouseEntered

    private void bg_bawahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg_bawahMouseEntered
        AnimationClass animm = new AnimationClass();
        //ImageIcon II = new ImageIcon(getClass().getResource("/Image/booking_1.png"));
        //booking_0.setIcon(II);
        //Booking
        animm.jLabelYDown(130, 230, 5, 5, trans_book);
        animm.jLabelYDown(190, 240, 10, 5, txt_booking);

        //Jadwal
        animm.jLabelYDown(130, 230, 5, 5, trans_jadwal);
        animm.jLabelYDown(190, 240, 10, 5, txt_jadwal);

        //Transaksi
        animm.jLabelYDown(130, 365, 5, 5, trans_transkasi);
        animm.jLabelYDown(260, 390, 5, 5, txt_trans);

        //Laporan
        animm.jLabelYDown(310, 390, 5, 5, trans_laporan);
        animm.jLabelYDown(360, 400, 5, 5, txt_laporan);

        ImageIcon II = new ImageIcon(getClass().getResource("/Image/close_off_1.png"));
        close.setIcon(II);

        ImageIcon IIq = new ImageIcon(getClass().getResource("/Image/min_1.png"));
        min.setIcon(IIq);
    }//GEN-LAST:event_bg_bawahMouseEntered

    private void trans_bookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trans_bookMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_trans_bookMouseClicked

    private void trans_bookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trans_bookMouseEntered

    }//GEN-LAST:event_trans_bookMouseEntered

    private void pilih_bookingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pilih_bookingMouseEntered
        AnimationClass animm = new AnimationClass();
        animm.jLabelYDown(130, 230, 5, 5, trans_jadwal);
        animm.jLabelYDown(190, 240, 10, 5, txt_jadwal);

        animm.jLabelYUp(230, 130, 5, 5, trans_book);

        animm.jLabelYUp(240, 190, 10, 5, txt_booking);

        //Laporan
        animm.jLabelYDown(310, 390, 5, 5, trans_laporan);
        animm.jLabelYDown(360, 400, 5, 5, txt_laporan);
    }//GEN-LAST:event_pilih_bookingMouseEntered

    private void trans_jadwalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trans_jadwalMouseEntered

    }//GEN-LAST:event_trans_jadwalMouseEntered

    private void pilih_jadwalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pilih_jadwalMouseEntered
        //Booking
        AnimationClass animm = new AnimationClass();
        animm.jLabelYDown(130, 230, 5, 5, trans_book);
        animm.jLabelYDown(190, 240, 10, 5, txt_booking);

        //Transaksi
        animm.jLabelYDown(130, 365, 5, 5, trans_transkasi);
        animm.jLabelYDown(260, 390, 5, 5, txt_trans);

        animm.jLabelYUp(230, 130, 5, 5, trans_jadwal);
        animm.jLabelYUp(240, 190, 10, 5, txt_jadwal);

        //Laporan
        animm.jLabelYDown(310, 390, 5, 5, trans_laporan);
        animm.jLabelYDown(360, 400, 5, 5, txt_laporan);
    }//GEN-LAST:event_pilih_jadwalMouseEntered

    private void pilih_transMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pilih_transMouseEntered
        AnimationClass animm = new AnimationClass();
        animm.jLabelYUp(365, 130, 5, 5, trans_transkasi);
        animm.jLabelYUp(390, 260, 5, 5, txt_trans);

        //Booking
        animm.jLabelYDown(130, 230, 5, 5, trans_book);
        animm.jLabelYDown(190, 240, 10, 5, txt_booking);

        //Jadwal
        animm.jLabelYDown(130, 230, 5, 5, trans_jadwal);
        animm.jLabelYDown(190, 240, 10, 5, txt_jadwal);

        //Laporan
        animm.jLabelYDown(310, 390, 5, 5, trans_laporan);
        animm.jLabelYDown(360, 400, 5, 5, txt_laporan);
    }//GEN-LAST:event_pilih_transMouseEntered

    private void pilih_laporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pilih_laporanMouseEntered
        AnimationClass animm = new AnimationClass();
        animm.jLabelYUp(390, 310, 5, 5, trans_laporan);
        animm.jLabelYUp(400, 360, 5, 5, txt_laporan);

        animm.jLabelYDown(130, 365, 5, 5, trans_transkasi);
        animm.jLabelYDown(260, 390, 5, 5, txt_trans);

    }//GEN-LAST:event_pilih_laporanMouseEntered

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Image/alas_close.png"));
        close.setIcon(II);

        ImageIcon IId = new ImageIcon(getClass().getResource("/Image/min_1.png"));
        min.setIcon(IId);
    }//GEN-LAST:event_closeMouseEntered

    private void minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Image/alas_min.png"));
        min.setIcon(II);

        ImageIcon IIa = new ImageIcon(getClass().getResource("/Image/close_off_1.png"));
        close.setIcon(IIa);
    }//GEN-LAST:event_minMouseEntered

    private void bar_atasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bar_atasMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Image/close_off_1.png"));
        close.setIcon(II);

        ImageIcon IIq = new ImageIcon(getClass().getResource("/Image/min_1.png"));
        min.setIcon(IIq);
    }//GEN-LAST:event_bar_atasMouseEntered

    private void pilih_bookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pilih_bookingMouseClicked
        Booking home = new Booking();
        home.setVisible(true);
    }//GEN-LAST:event_pilih_bookingMouseClicked

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        Frame frame = new Frame();
        frame.setState(Frame.ICONIFIED);

    }//GEN-LAST:event_minMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        int jawab = JOptionPane.showOptionDialog(this,
                "Ingin Keluar?",
                "Keluar",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null, null);

        if (jawab == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Program Akan Keluar");
            dispose();
        }
        //dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void pilih_jadwalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pilih_jadwalMouseClicked
        Jadwal jadwal = new Jadwal();
        jadwal.setVisible(true);
    }//GEN-LAST:event_pilih_jadwalMouseClicked

    private void pilih_transMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pilih_transMouseClicked
        Transaksi trans = new Transaksi();
        trans.setVisible(true);
    }//GEN-LAST:event_pilih_transMouseClicked

    private void trans_transkasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trans_transkasiMouseClicked
        Transaksi trans = new Transaksi();
        trans.setVisible(true);
    }//GEN-LAST:event_trans_transkasiMouseClicked

    private void pilih_laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pilih_laporanMouseClicked
        Laporan lap = new Laporan();
        lap.setVisible(true);
    }//GEN-LAST:event_pilih_laporanMouseClicked

    private void trans_laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trans_laporanMouseClicked
        Laporan lap = new Laporan();
        lap.setVisible(true);
    }//GEN-LAST:event_trans_laporanMouseClicked

    private void wasit_0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wasit_0MouseEntered
        //Transaksi
        AnimationClass animm = new AnimationClass();
        animm.jLabelYDown(130, 365, 5, 5, trans_transkasi);
        animm.jLabelYDown(260, 390, 5, 5, txt_trans);
    }//GEN-LAST:event_wasit_0MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Version;
    private javax.swing.JLabel bar_atas;
    private javax.swing.JLabel bar_samping;
    private javax.swing.JLabel bg_bawah;
    private javax.swing.JLabel bg_nutopbarbiru;
    private javax.swing.JLabel bg_nutopbarbiru1;
    private javax.swing.JLabel booking_0;
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jadwal_0;
    private javax.swing.JLabel laporan_0;
    private javax.swing.JLabel min;
    private javax.swing.JLabel pilih_booking;
    private javax.swing.JLabel pilih_jadwal;
    private javax.swing.JLabel pilih_laporan;
    private javax.swing.JLabel pilih_trans;
    private javax.swing.JLabel trans_book;
    private javax.swing.JLabel trans_jadwal;
    private javax.swing.JLabel trans_laporan;
    private javax.swing.JLabel trans_transkasi;
    private javax.swing.JLabel transaksi_0;
    private javax.swing.JLabel txt_BulanTahun;
    private javax.swing.JLabel txt_Tanggal;
    private javax.swing.JLabel txt_booking;
    private javax.swing.JLabel txt_jadwal;
    private javax.swing.JLabel txt_laporan;
    private javax.swing.JLabel txt_trans;
    private javax.swing.JLabel user1;
    private javax.swing.JLabel wasit_0;
    // End of variables declaration//GEN-END:variables
}
