
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Rizqi
 */
public class Jadwal extends javax.swing.JFrame {

    /**
     * Creates new form Jadwal
     */
    public DefaultTableModel tabel1;
    public Jadwal() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        setIcon();
        this.tabel1= (DefaultTableModel) Table1.getModel();
    }
     public void tabeljadwal(){
        tabel1.addColumn("No");
        tabel1.addColumn("Nama Team");
        tabel1.addColumn("No. HP");
        tabel1.addColumn("Tanggal");
        tabel1.addColumn("Jam Masuk");
        tabel1.addColumn("Jam Keluar");
        tabel1.addColumn("Sisa Bayar");
    
        try{
             Connection c = koneksi.getKon();
            Statement s = c.createStatement();

            String sql = "SELECT * FROM tbl_booking";

            ResultSet r = s.executeQuery(sql);
            while (r.next()) {
                tabel1.addRow(new Object[]{
                    r.getInt("no_booking"),
                    r.getString("nama_tim"),
                    r.getString("no_hp"),
                    r.getString("tanggal"),
                    r.getString("jam_masuk"),
                    r.getString("jam_keluar"),
                    r.getString("Sisa")

                });
            }
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan");
        }
    
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Image/LOGO.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sampai = new com.toedter.calendar.JDateChooser();
        dari = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_Cari = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        atas = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sampai.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(sampai, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 150, 30));

        dari.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(dari, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 160, 30));

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Table1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 280, 680, 170));

        jLabel4.setFont(new java.awt.Font("Open Sans Semibold", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tanggal awal");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Open Sans Semibold", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("S/D");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Open Sans Semibold", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tanggal akhir");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Laporan/baaa.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        btn_Cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jadwal/btn_cari.png"))); // NOI18N
        btn_Cari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CariMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_CariMouseEntered(evt);
            }
        });
        getContentPane().add(btn_Cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 230, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jadwal/close.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(768, 29, -1, -1));

        jLabel2.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 51, 69));
        jLabel2.setText("Cari Berdasarkan Tanggal");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 75, -1, -1));

        atas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jadwal/bar_atas.png"))); // NOI18N
        atas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                atasMouseDragged(evt);
            }
        });
        atas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                atasMousePressed(evt);
            }
        });
        getContentPane().add(atas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jadwal/bg.png"))); // NOI18N
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bgMouseEntered(evt);
            }
        });
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 20, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CariMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CariMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Jadwal/btn_cariOn.png"));
        btn_Cari.setIcon(II);
    }//GEN-LAST:event_btn_CariMouseEntered

    int xx, xy;
    private void atasMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atasMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_atasMouseDragged

    private void atasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atasMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_atasMousePressed

    private void bgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Jadwal/btn_cari.png"));
        btn_Cari.setIcon(II);
    }//GEN-LAST:event_bgMouseEntered

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btn_CariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CariMouseClicked
        // TODO add your handling code here:
        //menghapus terlebih dahulu isi tabel
        int row=tabel1.getRowCount();
        for (int i=0;i<row;i++){
            tabel1.removeRow(0);
          }
        //mengubah format jdchooser ke format sql
         java.sql.Date tanggal1 = new java.sql.Date(dari.getDate().getTime());
         java.sql.Date tanggal2 = new java.sql.Date(sampai.getDate().getTime());
         
         try{
              Connection c = koneksi.getKon();
              Statement s = c.createStatement();
              //membuat statement antara dua buah tanggal
                ResultSet r = s.executeQuery("select * from tbl_booking where tanggal between' "+tanggal1+ " ' "+"and ' "+tanggal2+ " ' ");
                    while (r.next()){
                        String[] data={r.getString(1), r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getString(7)};
                        tabel1.addRow(data);
                        }
         }catch(Exception e){
             JOptionPane.showMessageDialog(null, "Terjadi Kesalahan");
         }
    }//GEN-LAST:event_btn_CariMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
         tabeljadwal();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jadwal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table1;
    private javax.swing.JLabel atas;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btn_Cari;
    private com.toedter.calendar.JDateChooser dari;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser sampai;
    // End of variables declaration//GEN-END:variables
}
