
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Rizqi
 */
public class Transaksi extends javax.swing.JFrame {

    

    /**
     * Creates new form Transaksi
     */
    String nobooking;
    public Transaksi() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        setIcon();
        delete();
    }
    public void delete(){
          try {
            Connection c = koneksi.getKon();
            Statement s = c.createStatement();
            //Statement statement = (Statement) koneksi.getKon().createStatement();
            s.executeUpdate("DELETE from tbl_tempotransaksi where no_booking=(' " + nobooking + " ');");
           
          }catch(Exception e){
          
          }
    }
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Image/LOGO.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_sisabayar = new javax.swing.JLabel();
        txt_sisa = new javax.swing.JTextField();
        txt_harga = new javax.swing.JLabel();
        txtfield_harga = new javax.swing.JTextField();
        txt_nama_team = new javax.swing.JLabel();
        txt_namateam = new javax.swing.JTextField();
        txt_no_book = new javax.swing.JLabel();
        txt_booking = new javax.swing.JTextField();
        txtfield_bayar2 = new javax.swing.JTextField();
        txt_kembalian1 = new javax.swing.JLabel();
        txt_kembalian = new javax.swing.JLabel();
        txtfield_bayar = new javax.swing.JTextField();
        txt_tgl = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_harga2 = new javax.swing.JLabel();
        txt_harga1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_cetak = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_close = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_sisabayar.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 20)); // NOI18N
        txt_sisabayar.setForeground(new java.awt.Color(30, 51, 69));
        txt_sisabayar.setText("Sisa Bayar");
        getContentPane().add(txt_sisabayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 155, -1, -1));

        txt_sisa.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        txt_sisa.setForeground(new java.awt.Color(75, 75, 77));
        txt_sisa.setCaretColor(new java.awt.Color(30, 51, 69));
        getContentPane().add(txt_sisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 130, 30));

        txt_harga.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 20)); // NOI18N
        txt_harga.setForeground(new java.awt.Color(58, 84, 106));
        txt_harga.setText("Rp");
        getContentPane().add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 155, -1, -1));

        txtfield_harga.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        txtfield_harga.setForeground(new java.awt.Color(75, 75, 77));
        txtfield_harga.setCaretColor(new java.awt.Color(30, 51, 69));
        getContentPane().add(txtfield_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 130, 30));

        txt_nama_team.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 20)); // NOI18N
        txt_nama_team.setForeground(new java.awt.Color(30, 51, 69));
        txt_nama_team.setText("Nama Team");
        getContentPane().add(txt_nama_team, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 155, -1, -1));

        txt_namateam.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        txt_namateam.setForeground(new java.awt.Color(75, 75, 77));
        txt_namateam.setCaretColor(new java.awt.Color(30, 51, 69));
        txt_namateam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_namateamKeyPressed(evt);
            }
        });
        getContentPane().add(txt_namateam, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 160, 30));

        txt_no_book.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 20)); // NOI18N
        txt_no_book.setForeground(new java.awt.Color(30, 51, 69));
        txt_no_book.setText("No Booking");
        getContentPane().add(txt_no_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 105, -1, -1));

        txt_booking.setEditable(false);
        txt_booking.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        txt_booking.setForeground(new java.awt.Color(75, 75, 77));
        txt_booking.setCaretColor(new java.awt.Color(30, 51, 69));
        getContentPane().add(txt_booking, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 160, 30));

        txtfield_bayar2.setEditable(false);
        txtfield_bayar2.setBackground(new java.awt.Color(86, 154, 214));
        txtfield_bayar2.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 48)); // NOI18N
        txtfield_bayar2.setForeground(new java.awt.Color(255, 255, 255));
        txtfield_bayar2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtfield_bayar2.setText(",-");
        txtfield_bayar2.setBorder(null);
        txtfield_bayar2.setCaretColor(new java.awt.Color(255, 255, 255));
        txtfield_bayar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtfield_bayar2MouseClicked(evt);
            }
        });
        txtfield_bayar2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfield_bayar2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfield_bayar2KeyReleased(evt);
            }
        });
        getContentPane().add(txtfield_bayar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 239, 30, 60));

        txt_kembalian1.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 48)); // NOI18N
        txt_kembalian1.setForeground(new java.awt.Color(255, 255, 255));
        txt_kembalian1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_kembalian1.setText(",-");
        getContentPane().add(txt_kembalian1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, 30, 60));

        txt_kembalian.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 48)); // NOI18N
        txt_kembalian.setForeground(new java.awt.Color(255, 255, 255));
        txt_kembalian.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_kembalian.setText("0");
        getContentPane().add(txt_kembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 239, 220, 60));

        txtfield_bayar.setBackground(new java.awt.Color(86, 154, 214));
        txtfield_bayar.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 48)); // NOI18N
        txtfield_bayar.setForeground(new java.awt.Color(255, 255, 255));
        txtfield_bayar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtfield_bayar.setBorder(null);
        txtfield_bayar.setCaretColor(new java.awt.Color(255, 255, 255));
        txtfield_bayar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtfield_bayarMouseClicked(evt);
            }
        });
        txtfield_bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfield_bayarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfield_bayarKeyReleased(evt);
            }
        });
        getContentPane().add(txtfield_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 210, 60));

        txt_tgl.setBackground(new java.awt.Color(86, 154, 214));
        txt_tgl.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 48)); // NOI18N
        txt_tgl.setForeground(new java.awt.Color(86, 154, 214));
        txt_tgl.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_tgl.setBorder(null);
        txt_tgl.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_tgl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_tglMouseClicked(evt);
            }
        });
        txt_tgl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_tglKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_tglKeyReleased(evt);
            }
        });
        getContentPane().add(txt_tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 210, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image.FormTransaksi/kembali.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, -1, -1));

        txt_harga2.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 20)); // NOI18N
        txt_harga2.setForeground(new java.awt.Color(58, 84, 106));
        txt_harga2.setText("Rp");
        getContentPane().add(txt_harga2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 105, -1, -1));

        txt_harga1.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 20)); // NOI18N
        txt_harga1.setForeground(new java.awt.Color(30, 51, 69));
        txt_harga1.setText("Harga");
        getContentPane().add(txt_harga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 105, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image.FormTransaksi/bayar.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        btn_cetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image.FormTransaksi/Cetak_off.png"))); // NOI18N
        btn_cetak.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cetak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cetakMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cetakMouseEntered(evt);
            }
        });
        getContentPane().add(btn_cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 330, -1, -1));

        btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image.FormTransaksi/Simpan_off.png"))); // NOI18N
        btn_simpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_simpanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_simpanMouseEntered(evt);
            }
        });
        getContentPane().add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image.FormTransaksi/abu2.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image.FormTransaksi/abu2.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image.FormTransaksi/close.png"))); // NOI18N
        btn_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image.FormTransaksi/bar_atas.png"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image.FormTransaksi/bg.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 25, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpanMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Image.FormTransaksi/Simpan_on.png"));
        btn_simpan.setIcon(II);
    }//GEN-LAST:event_btn_simpanMouseEntered

    private void btn_cetakMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cetakMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Image.FormTransaksi/Cetak_on.png"));
        btn_cetak.setIcon(II);
    }//GEN-LAST:event_btn_cetakMouseEntered

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Image.FormTransaksi/Simpan_off.png"));
        btn_simpan.setIcon(II);

        ImageIcon IIk = new ImageIcon(getClass().getResource("/Image.FormTransaksi/Cetak_off.png"));
        btn_cetak.setIcon(IIk);
    }//GEN-LAST:event_jLabel2MouseEntered

    int xx, xy;
    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        txtfield_bayar.requestFocus();
        try {
            Connection c = koneksi.getKon();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery("select * from tbl_booking where " + "no_booking=' " + txt_booking.getText() + " ' ");

            while (r.next()) {
                //mengakses data pada database
                txt_namateam.setText(r.getString("nama_tim"));
                txtfield_harga.setText(r.getString("harga"));
                txt_sisa.setText(r.getString("sisa"));
                txt_tgl.setText(r.getString("tanggal"));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
        }

    }//GEN-LAST:event_formWindowActivated

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_closeMouseClicked

    private void btn_cetakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cetakMouseClicked
        // TODO add your handling code here:
          try {
          
            //String NamaFile = "./src/transaksi.jrxml";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/db_futsal", "root", "");
            
            InputStream file = getClass().getResourceAsStream("/transaksi.jrxml");
            JasperDesign jasperDesign = JRXmlLoader.load(file);
            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
            Map<String, Object> par = new HashMap<String, Object>();
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, par, koneksi);
            JasperViewer.viewReport(jasperPrint, false);
           delete();
           dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "tidak dapat menampilkan laporan");
        }


    }//GEN-LAST:event_btn_cetakMouseClicked
       
    private void txtfield_bayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfield_bayarKeyReleased
        // TODO add your handling code here:
        int total;
        int bayar = Integer.parseInt(txtfield_bayar.getText());
        int sisa = Integer.parseInt(txt_sisa.getText());

        total = bayar - sisa;

        String kembalian = String.valueOf(total);
        txt_kembalian.setText("" + kembalian);
    }//GEN-LAST:event_txtfield_bayarKeyReleased

    private void txtfield_bayarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfield_bayarMouseClicked
        txtfield_bayar.setText("");
    }//GEN-LAST:event_txtfield_bayarMouseClicked

    private void txt_namateamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_namateamKeyPressed

    }//GEN-LAST:event_txt_namateamKeyPressed

    private void txtfield_bayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfield_bayarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btn_simpan.requestFocus();
            evt.consume();
        }

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtfield_bayar.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Pembayaran tidak boleh kosong");
                txtfield_bayar.requestFocus();
            }
        }
    }//GEN-LAST:event_txtfield_bayarKeyPressed

    String jam_masuk, jam_keluar, nama_tim, tanggal;
    int harga, sisa, jam, no_booking;
    private void btn_simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpanMouseClicked
        nobooking = txt_booking.getText();
        int bayar = Integer.parseInt(txtfield_bayar.getText());
        int kembalian = Integer.parseInt(txt_kembalian.getText());
        tanggal = txt_tgl.getText();
        try {
            Connection c = koneksi.getKon();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery("select * from tbl_booking where " + "no_booking=' " + txt_booking.getText() + " ' ");

            while (r.next()) {

                //mengisi variable berdasarkan database tbl_login
                no_booking = (r.getInt("no_booking"));
                nama_tim = (r.getString("nama_tim"));
                jam_masuk = (r.getString("jam_masuk"));
                jam_keluar = (r.getString("jam_keluar"));
               // tanggal = (r.getString("tanggal"));
                harga = (r.getInt("harga"));
                sisa = (r.getInt("sisa"));
                jam = (r.getInt("jam"));
            }
            try {
                //input kedatabase tabel transaski untuk print laporan
                s.executeUpdate("Insert into tbl_transaksi VALUES (' " + no_booking + " ', ' " + nama_tim + " ', ' " + tanggal + " ' , ' " + jam_masuk
                        + " ' , ' " + jam_keluar + " ' , ' " + harga + " ', ' " + sisa + " ', ' "
                        + jam + " ', ' " + bayar + " ' , ' " + kembalian + " ' );");
                //input kedatabase tabel tempotransaksi untuk print nota
                 s.executeUpdate("Insert into tbl_tempotransaksi VALUES (' " + no_booking + " ', ' " + nama_tim + " ', ' " + tanggal + " ' , ' " + jam_masuk
                        + " ' , ' " + jam_keluar + " ' , ' " + harga + " ', ' " + sisa + " ', ' "
                        + jam + " ', ' " + bayar + " ' , ' " + kembalian + " ' );");
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
        }
    }//GEN-LAST:event_btn_simpanMouseClicked

    private void txtfield_bayar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfield_bayar2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield_bayar2MouseClicked

    private void txtfield_bayar2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfield_bayar2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield_bayar2KeyPressed

    private void txtfield_bayar2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfield_bayar2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield_bayar2KeyReleased

    private void txt_tglMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_tglMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tglMouseClicked

    private void txt_tglKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tglKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tglKeyPressed

    private void txt_tglKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tglKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tglKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_cetak;
    private javax.swing.JLabel btn_close;
    private javax.swing.JLabel btn_simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JTextField txt_booking;
    private javax.swing.JLabel txt_harga;
    private javax.swing.JLabel txt_harga1;
    private javax.swing.JLabel txt_harga2;
    private javax.swing.JLabel txt_kembalian;
    private javax.swing.JLabel txt_kembalian1;
    private javax.swing.JLabel txt_nama_team;
    private javax.swing.JTextField txt_namateam;
    private javax.swing.JLabel txt_no_book;
    private javax.swing.JTextField txt_sisa;
    private javax.swing.JLabel txt_sisabayar;
    public static javax.swing.JTextField txt_tgl;
    private javax.swing.JTextField txtfield_bayar;
    private javax.swing.JTextField txtfield_bayar2;
    private javax.swing.JTextField txtfield_harga;
    // End of variables declaration//GEN-END:variables
}
